### ISSUE TITLE
Fails to parse error response

### ISSUE THREAD

**Issue by yuri-tceretian** [signnow/SignNow.NET#134]
When I run the library against sandbox API that seemed to be down at that time I got a response that was not expected by the response handler.

```
SignNow.Net.Exceptions.SignNowException : Newtonsoft.Json.JsonReaderException thrown while parsing Json body from https://api-eval.signnow.com/oauth2/token (Invalid Json syntax in response (Unexpected character encountered while parsing value: [. Path 'error', line 1, position 10.))
Data:
  RawHeaders: System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.IEnumerable`1[System.String]]
  RawResponse: {"error":[{"code":"HY000","message":"Internal Api Error"}]}
  HttpStatusCode: 500
  ----> SignNow.Net.Exceptions.SignNowException : Invalid Json syntax in response (Unexpected character encountered while parsing value: [. Path 'error', line 1, position 10.)
  ----> Newtonsoft.Json.JsonReaderException : Unexpected character encountered while parsing value: [. Path 'error', line 1, position 10.
   at SignNow.Net.Internal.Service.SignNowClient.ProcessErrorResponse(RequestOptions requestOptions, HttpResponseMessage response)
   at SignNow.Net.Internal.Service.SignNowClient.RequestAsync[TResponse](RequestOptions requestOptions, IHttpContentAdapter`1 adapter, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at SignNow.Net.Internal.Service.SignNowClient.RequestAsync[TResponse](RequestOptions requestOptions, CancellationToken cancellationToken)
   at SignNow.Net.OAuth2Service.ExecuteTokenRequest(Dictionary`2 body, CancellationToken cancellationToken)
   at SignNow.Net.OAuth2Service.GetTokenAsync(String login, String password, Scope scope, CancellationToken cancellationToken)
--SignNowException
```

**Comment by AlexNDRmac** [comment]
Thanks for the report. We had some issue with Sandbox, now it works. Also, I'll check error handler.

**Comment by AlexNDRmac** [comment]
Thank you, fix is already merged into develop branch.

**Comment by rawedit** [comment]
I'm using the current develop branch to make calls to the Sandbox and I'm getting the following exception, please can you advise?

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[14].json_attributes', line 1, position 6137.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at SignNow.Net.Internal.Helpers.HttpContentToObjectAdapter`1.Adapt(HttpContent content)
   at SignNow.Net.Internal.Service.SignNowClient.RequestAsync[TResponse](RequestOptions requestOptions, IHttpContentAdapter`1 adapter, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at SignNow.Net.Internal.Service.SignNowClient.RequestAsync[TResponse](RequestOptions requestOptions, CancellationToken cancellationToken)
   at SignNow.Net.Service.DocumentService.GetDocumentHistoryAsync(String documentId, CancellationToken cancellationToken)
   at TemplateEngineApi.Services.ESignatureService.GetDocumentHistory(String documentId) in ...
   at TemplateEngineApi.Controllers.ESignatureController.GetDocumentHistory(String documentId) in ...
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
